"""Shared constants for seqopt."""

AMINO_ACIDS = "ACDEFGHIKLMNPQRSTVWY"

TARGET = (
    "EYWWPYKYYRHVMQQVGGKWQIMRGTGFEWNFFEAIRNWITYAYSVALKGMIAKYTPVTWWNPSDTFYDAEHEGFCDLLRILYVSWVRVRDCCGTYKTRVSWKQDL"
)
ANTITARGET = (
    "MQTETIGHKSPSFEYLEGYHHRIQGNRDCWACWGKVLCLFIVCMLHEKTYAESSPWIQKENCWMWNINKVSCVRFEWRYCHGPVTLHMASAFQLKHVYLLIAYTPTNPMYDTVFHDNCEWAQTPGNFWACQQIF"
)

